[build]
  publish = "radar"

[[headers]]
  for = "/latest.json"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "public, max-age=300"
