function esc(s) { return String(s || '').replace(/[&<>"']/g, function (c) { return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]; }); }
function date(iso) { if (!iso) return '时间未识别'; return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso)); }

export function renderHtml(report) {
  const cards = report.top5.map(function (x, i) {
    return '<article class="card"><div class="rank">#' + (i+1) + '</div><div class="score">' + x.score + '<small>分</small></div><div class="body"><div class="meta">' + esc(x.sourceName) + ' · ' + date(x.publishedAt) + '</div><h2>' + esc(x.title) + '</h2><p class="reason">' + esc(x.reason) + '</p><div class="pill">' + esc(x.angle) + '</div><p class="decision">' + esc(x.decision) + '</p><a href="' + esc(x.url) + '" target="_blank" rel="noreferrer">查看原始信号 ↗</a></div></article>';
  }).join('');
  const pool = report.candidates.slice(5,15).map(function (x,i) { return '<li><span>' + (i+6) + '</span><div><b>' + esc(x.title) + '</b><small>' + esc(x.sourceName) + ' · ' + x.score + '分 · ' + esc(x.angle) + '</small></div></li>'; }).join('');
  const sources = report.sources.map(function (s) { return '<li class="source ' + (s.ok ? 'ok':'bad') + '"><span>' + (s.ok ? '○':'×') + '</span>' + esc(s.name) + '<small>' + (s.ok ? s.count + '条' : esc(s.error || '失败')) + '</small></li>'; }).join('');
  return ['<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>江浙沪团建雷达</title>',
  '<style>:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;color:#171717;background:#f6f6f3}*{box-sizing:border-box}body{margin:0}.wrap{max-width:860px;margin:auto;padding:22px 14px 60px}.hero{background:#111;color:#fff;border-radius:22px;padding:24px;margin-bottom:16px}.hero h1{margin:0 0 8px;font-size:28px}.hero p{margin:0;color:#bbb;line-height:1.6}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-top:18px}.stat{background:#222;border-radius:13px;padding:12px}.stat b{font-size:22px;display:block}.stat small{color:#aaa}.section{font-size:18px;margin:24px 2px 12px}.card{display:grid;grid-template-columns:48px 58px 1fr;gap:10px;background:#fff;border:1px solid #e7e7e2;border-radius:18px;padding:16px;margin:10px 0;box-shadow:0 4px 20px rgba(0,0,0,.025)}.rank{font-weight:800;font-size:18px}.score{font-size:28px;font-weight:800}.score small{font-size:12px;margin-left:2px;color:#777}.body h2{font-size:19px;margin:4px 0 8px;line-height:1.35}.meta,.decision{font-size:13px;color:#777}.reason{line-height:1.6;margin:8px 0}.pill{display:inline-block;background:#f0f0eb;border-radius:999px;padding:5px 9px;font-size:12px;font-weight:600}.body a{display:inline-block;margin-top:8px;color:#111;font-size:13px}.pool,.sources{list-style:none;margin:0;padding:0;background:#fff;border:1px solid #e7e7e2;border-radius:16px;overflow:hidden}.pool li{display:flex;gap:12px;padding:12px 14px;border-bottom:1px solid #eee}.pool li:last-child,.sources li:last-child{border-bottom:0}.pool li>span{font-weight:800;color:#999}.pool b{display:block;font-size:14px}.pool small{display:block;margin-top:4px;color:#777}.sources li{display:flex;gap:8px;align-items:center;padding:10px 14px;border-bottom:1px solid #eee;font-size:13px}.sources li small{margin-left:auto;color:#888}.source.ok>span{color:#239a55}.source.bad>span{color:#c33}.foot{margin-top:22px;color:#999;font-size:12px;line-height:1.7}@media(max-width:600px){.wrap{padding:14px 10px 40px}.hero{padding:20px}.hero h1{font-size:24px}.card{grid-template-columns:38px 52px 1fr;padding:13px;gap:6px}.body h2{font-size:17px}.stat{padding:10px}.stat b{font-size:19px}}</style></head><body><main class="wrap">',
  '<section class="hero"><h1>江浙沪团建雷达</h1><p>今天最值得生产什么，一眼看完。当前模式：' + esc(report.mode) + '</p><div class="stats"><div class="stat"><b>' + report.meta.sourceCount + '</b><small>信源</small></div><div class="stat"><b>' + report.meta.candidateCount + '</b><small>候选</small></div><div class="stat"><b>' + report.top5.length + '</b><small>今日机会</small></div></div></section>',
  '<h3 class="section">🔥 今日 Top 5</h3>' + (cards || '<p>今天还没有有效候选。</p>'),
  '<h3 class="section">候选池</h3><ul class="pool">' + (pool || '<li>暂无更多候选</li>') + '</ul>',
  '<h3 class="section">信源状态</h3><ul class="sources">' + sources + '</ul>',
  '<p class="foot">生成时间：' + esc(report.meta.generatedAt) + '（Asia/Shanghai）<br>排序原则：官方变化 → 用户需求价值 → 同行/市场验证。这个页面只负责回答“今天值得做什么”，生产交给现有内容工作流。</p>',
  '</main></body></html>'].join('');
}
